### ISSUE TITLE
hostnames vs IP addresses

### ISSUE THREAD

**Issue by DG12** [hpirila/ESP32-Ruuvitag-Collector#1]
Could you use 

 dns_gethostbyname(szURL, &ip_Addr, dns_found_cb, NULL );

to resolve ip_Addr from hostname?

**Comment by hpirila** [comment]
The DNS resolving is not very easy with ESP32 and therefore I don't use it. More information here https://www.esp32.com/viewtopic.php?t=2268.

The Influx, MQTT and NTP server IP's needed here are often static enough and it is better to use IP also for faster and more reliable functionality. To get the ip in first place use example ping command.
