### ISSUE TITLE
Use WiFiManager for easier connectivity

### ISSUE THREAD

**Issue by aapris** [hpirila/ESP32-Ruuvitag-Collector#2]
Feature request: if WiFiManager is used, it would be much easier to deploy Ruuvitag-Collectors. If pre-configured WiFi is not available, then Ruuvitag-Collector starts a hotspot and waits for WiFi configuration in captive portal.

Currently it is not possible to change WiFi credentials or move Collector to another WiFi without re-flashing the device.

**Comment by hpirila** [comment]
I know wifi manager but its not my favorite and I will not implement it - decided already before this issue. Feel free to fork or clone the project and implement it.

**Comment by aapris** [comment]
I already forked. :)
